### ISSUE TITLE
Mounting a custom ossec.conf would prevent files from being installed in /var/ossec/data/etc

### ISSUE THREAD

**Issue by laukaichung** [xetus-oss/docker-ossec-server#7]
How can I mount a custom ossec.conf with docker-compose without any error? 
If I mount a custom `ossec.conf` in `/var/ossec/data/etc/ossec.conf`, the entry point script (run.bash) would skip installing some files in `/var/ossec/data/etc` because it notes that the `/var/ossecdata/etc` folder exists. I've tried both ossec/ossec-docker and xetus-oss/docker-ossec-server, and it seems that the problem comes from this part in the entrypoint script:

run.bash
````
DATA_DIRS="etc rules logs stats queue"
for ossecdir in $DATA_DIRS; do
	if [ ! -e "${DATA_PATH}/${ossecdir}" ]; then
    		echo "Installing ${ossecdir}"
		mkdir -p ${DATA_PATH}/${ossecdir}
    		cp -a /var/ossec/${ossecdir}-template/* ${DATA_PATH}/${ossecdir}/ 2>/dev/null
    		FIRST_TIME_INSTALLATION=true
  	fi
done
````

docker-compose.yml
````
version: '3.4'

services:
  ossec:
    container_name: ossec
    image: xetus-oss/docker-ossec-server
    restart: alway
    volumes:
      - ./ossec.conf:/var/ossec/data/etc/ossec.conf
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
````

docker-compose run ossec
````
ossec    | Installing rules <<=== missing Installing etc
ossec    | Installing logs
ossec    | Installing stats
ossec    | Installing queue
ossec    | Bulk load file: /var/ossec/default_agent
ossec    | Opening: [/var/ossec/default_agent]
ossec    | Agent information:
ossec    |    ID:001
ossec    |    Name:DEFAULT_LOCAL_AGENT
ossec    |    IP Address:127.0.0.1
ossec    | 
ossec    | Agent added.
ossec    | Starting OSSEC HIDS 2.9.2 (by Trend Micro Inc.)...
ossec    | OSSEC analysisd: Testing rules failed. Configuration error. Exiting.
ossec    | 2018/02/05 06:23:35 ossec-authd: INFO: Started (pid: 21).
ossec    | 2018/02/05 06:23:35 getaddrinfo: Name or service not known
ossec    | 2018/02/05 06:23:35 ossec-authd: Unable to bind to port 1515
ossec    | 2018/02/05 06:23:52 ossec-analysisd(1226): ERROR: Error reading XML file 'etc/decoder.xml': XMLERR: File 'etc/decoder.xml' not found. (line 203).
ossec    | 2018/02/05 06:23:52 ossec-testrule(1202): ERROR: Configuration error at '/etc/decoder.xml'. Exiting.
````

**Comment by tkent** [comment]
@stonecold123 

This container isn't intended to allow you to pre-seed only an `ossec.conf` file. The data separation for container is designed to be all-or-nothing thing, as you discovered. The intent was that you could customize your OSSEC configuration after the initial setup. All your configuration and agent data can then be moved around with the volume.

That said, there is a way for you to accomplish what you're looking to do. The trick will be to mount your custom ossec.conf file over the existing template file in the container. That way, your custom configuration file gets copied during the `run.bash` execution.

Here's an example of how you would do that (note the first volume mount):

```
docker run --name ossec-server -d -p 1514:1514/udp -p 1515:1515\
  -v /my/custom/ossec.conf:/var/ossec/etc/ossec.conf \
  -v /somepath/ossec_mnt:/var/ossec/data xetusoss/ossec-server
```

In the context of your docker compose file, the solution would look like:

```
version: '3.4'

services:
  ossec:
    container_name: ossec
    image: xetus-oss/docker-ossec-server
    restart: alway
    volumes:
      - ./ossec.conf:/var/ossec/etc/ossec.conf
      - ./ossec_data_dir:/var/ossec/data
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
```
